# python -u extract_papers.py https://dblp.org/db/conf/kbse/ase2024.html https://conf.researchr.org/track/ase-2024/ase-2024-research "Research Papers"
# python -u extract_papers.py https://dblp.org/db/journals/pacmse/pacmse1.html#nrFSE https://conf.researchr.org/track/fse-2024/fse-2024-research-papers "Research Papers"
# python -u extract_papers.py https://dblp.org/db/conf/icse/icse2024.html https://conf.researchr.org/track/icse-2024/icse-2024-research-track "Research Track"
# python -u extract_papers.py https://dblp.org/db/conf/re/re2024.html https://conf.researchr.org/track/RE-2024/RE-2024-Research-Papers "Research Papers"
# python -u extract_papers.py https://dblp.org/db/conf/ease/ease2024.html https://conf.researchr.org/track/ease-2024/ease-2024-papers "Research Papers"
# python -u extract_papers.py https://dblp.org/db/conf/ecsa/ecsa2024.html https://conf.researchr.org/track/ecsa-2024/ecsa-2024-research-papers "Research Papers"
# python -u extract_papers.py https://dblp.org/db/conf/esem/esem2024.html https://conf.researchr.org/track/esem-2024/esem-2024-technical-track "ESEM Technical Papers"
# python -u extract_papers.py https://dblp.org/db/conf/iwpc/icpc2024.html https://conf.researchr.org/track/icpc-2024/icpc-2024-research "Research Track"
# python -u extract_papers.py https://dblp.org/db/conf/icsa/icsa2024.html https://conf.researchr.org/track/icsa-2024/icsa-2024-papers "Research Papers"
# python -u extract_papers.py https://dblp.org/db/conf/icsm/icsme2024.html https://conf.researchr.org/track/icsme-2024/icsme-2024-papers "Research Track"
# python -u extract_papers.py https://dblp.org/db/conf/icst/icst2024.html https://conf.researchr.org/track/icst-2024/icst-2024-papers "Research Papers"
# python -u extract_papers.py https://dblp.org/db/conf/issta/issta2024.html https://conf.researchr.org/track/issta-2024/issta-2024-papers "Technical Papers"
# python -u extract_papers.py https://dblp.org/db/conf/models/models2024.html https://conf.researchr.org/track/models-2024/models-2024-technical-track "Technical Track"
# python -u extract_papers.py https://dblp.org/db/conf/msr/msr2024.html https://2024.msrconf.org/track/msr-2024-technical-papers "Technical Papers"
# python -u extract_papers.py https://dblp.org/db/conf/wcre/saner2024.html https://conf.researchr.org/track/saner-2024/saner-2024-papers "Research Papers"
# python -u extract_papers.py https://dblp.org/db/conf/seams/seams2024.html https://conf.researchr.org/track/seams-2024/seams-2024-research-track#event-overview "Research Track"

# python -u crawldblp.py https://dblp.org/db/conf/kbse/ase2024.html https://conf.researchr.org/track/ase-2024/ase-2024-research "Research Papers"
# python -u crawldblp.py https://dblp.org/db/journals/pacmse/pacmse1.html#nrFSE https://conf.researchr.org/track/fse-2024/fse-2024-research-papers "Research Papers"
# python -u crawldblp.py https://dblp.org/db/conf/icse/icse2024.html https://conf.researchr.org/track/icse-2024/icse-2024-research-track "Research Track"
# python -u crawldblp.py https://dblp.org/db/conf/re/re2024.html https://conf.researchr.org/track/RE-2024/RE-2024-Research-Papers "Research Papers"
# python -u crawldblp.py https://dblp.org/db/conf/ease/ease2024.html https://conf.researchr.org/track/ease-2024/ease-2024-papers "Research Papers"
# python -u crawldblp.py https://dblp.org/db/conf/ecsa/ecsa2024.html https://conf.researchr.org/track/ecsa-2024/ecsa-2024-research-papers "Research Papers"
# python -u crawldblp.py https://dblp.org/db/conf/esem/esem2024.html https://conf.researchr.org/track/esem-2024/esem-2024-technical-track "ESEM Technical Papers"
# python -u crawldblp.py https://dblp.org/db/conf/iwpc/icpc2024.html https://conf.researchr.org/track/icpc-2024/icpc-2024-research "Research Track"
# python -u crawldblp.py https://dblp.org/db/conf/icsa/icsa2024.html https://conf.researchr.org/track/icsa-2024/icsa-2024-papers "Research Papers"
# python -u crawldblp.py https://dblp.org/db/conf/icsm/icsme2024.html https://conf.researchr.org/track/icsme-2024/icsme-2024-papers "Research Track"
# python -u crawldblp.py https://dblp.org/db/conf/icst/icst2024.html https://conf.researchr.org/track/icst-2024/icst-2024-papers "Research Papers"
# python -u crawldblp.py https://dblp.org/db/conf/issre/issre2024.html
# python -u crawldblp.py https://dblp.org/db/conf/issta/issta2024.html https://conf.researchr.org/track/issta-2024/issta-2024-papers "Technical Papers"
python -u crawldblp.py https://dblp.org/db/conf/models/models2024.html https://conf.researchr.org/track/models-2024/models-2024-technical-track "Technical Track"
# python -u crawldblp.py https://dblp.org/db/conf/msr/msr2024.html https://2024.msrconf.org/track/msr-2024-technical-papers "Technical Papers"
# python -u crawldblp.py https://dblp.org/db/conf/wcre/saner2024.html https://conf.researchr.org/track/saner-2024/saner-2024-papers "Research Papers"
# python -u crawldblp.py https://dblp.org/db/conf/seams/seams2024.html https://conf.researchr.org/track/seams-2024/seams-2024-research-track#event-overview "Research Track"
